### ISSUE TITLE
Trigger fanart grabber when selecting fanart source

### ISSUE THREAD

**Issue by jeroenpardon** [jeroenpardon/skin.grid#136]

**Comment by Ostrymiecz** [comment]
Any news on this Jeroen?

**Comment by jeroenpardon** [comment]
If I change or fix something, the issue will be updated. If there is nothing, there is no news.

**Comment by Ostrymiecz** [comment]
WOW. You could also write "f*ck you and get lost". It would sound the same. Jesus… What's wrong with You lately? 😞

**Comment by jeroenpardon** [comment]
Ehm, ok... maybe you could try calming down as you are totally overreacting and misinterpreting. In any case this stops here, this is an issue tracker.

**Comment by Ostrymiecz** [comment]
OK. I'm waiting then.

**Comment by jeroenpardon** [comment]
Closing this because of the impending replacement of fanart grabber
