### ISSUE TITLE
Video progress bar logic

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#142]
The time on the progress bar shows the remaining time of the playing video (it counts down). While the progress bar itself progresses to the end of the video (it adds up).
Imho there could be two options: 

1. The remaining time text has to be on the right of the progress bar where the remaining time and the remaining space of the progress bar are equal.
2. You show the start time on the left and the end time on the right.

Also, the 'seeking: xx:xx' replaces the remaining time in the current design. Imho this makes seeking harder.

![image](https://user-images.githubusercontent.com/1034920/31862124-6d339996-b739-11e7-9a5e-d622d78cf65f.png)

**Comment by jeroenpardon** [comment]
Although I don't particularly think the placement of the time itself and the progress indicator need to be related strictly, I get what you mean about the seeking label replacing the time. Have to think about it, cheers

**Comment by Joostzilla** [comment]
Sure! I think when seeking for instance +10:00 while the time actually lowers 10 minutes it could be unclear. At least for me.

**Comment by jeroenpardon** [comment]
So 3498fb97ff5133d06d7000bd7ff8ffd0b58cf100 gives several options for showing player progression. As for the positioning though, that will remain left aligned.
