### ISSUE TITLE
Recording thumbs are replaces by fanart in Listview

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#143]
In Recordings listview the scraped thumbs are replaced by fanart thumbs.
When looking through other views the scaped images are there.

![image](https://user-images.githubusercontent.com/1034920/31862196-4388f25c-b73a-11e7-97cb-553c17de927c.png)
![image](https://user-images.githubusercontent.com/1034920/31862179-1d1b4ea8-b73a-11e7-93af-21d0eadb6f28.png)
![image](https://user-images.githubusercontent.com/1034920/31862185-26158d3e-b73a-11e7-83c9-4b8c3bf263b4.png)

**Comment by jeroenpardon** [comment]
This discrepancy exists because in list view the fanart is pulled in by the Skin Helper add-on's PVR scraper and stored in a property that, due to Kodi limitations, can only be rendered outside of the actual list control. In other words, in views where the image control is part of the scrollable list itself, the artwork cannot be shown.

**Comment by Joostzilla** [comment]
So that's basically a bad thing! It would be better if the actual episode thumbs would show in List view.

**Comment by Joostzilla** [comment]
I guess i will browse recordings in big list view only then :-)

**Comment by jeroenpardon** [comment]
A way to remedy this would be to have a skin setting that disables the PVR artwork scraper. That would mean it'll be disabled everywhere though, not just recordings.

**Comment by Joostzilla** [comment]
The recording thumbs are created by my dvblink tvserver. These are actual recorded frames. 
The scraped art is just a general image of the recorded programme. So not of the actual recording. 
Disabling art scraping would be no problem for me but as i understand not all tvserver backends support recording frames

**Comment by jeroenpardon** [comment]
6ddf74c1b29cc59d2a761aa79b55653606621820 introduces an option to disable the pvr scraper in skin settings > pvr
