### ISSUE TITLE
Optimize Recording notification 

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#144]
At this moment the only way of knowing when a recording is timed is going to the timer page.
Maybe a recording icon (as in the LiveTV popup guide) or a signalcolor should be in the TV guide.
The same goes for current recordings.

The color option only works when users don't use genre colors.

**Comment by jeroenpardon** [comment]
There is  a way to see it in the guide actually, but you modded it out ;) It's on the second line, but that has always been a stop-gap solution really. Thinking about doing something like this:

![image](https://i.imgur.com/0ugeMJ7.png)

And use a different color for non-recording timers. I will have to tweak the genre colours though, or else it will not work out.

**Comment by Joostzilla** [comment]
Haha, i had no idea it was on the second line.
The red line could be a good idea. 
I wish i could disable the genre colors. 
The green color you have in the above screenshot is a great color for the guide without genre colors. 
In that case recordings could be completely red.

**Comment by jeroenpardon** [comment]
Yeah, but even then there would need to be a way to indicate recordings when genre colors are enabled.

**Comment by Joostzilla** [comment]
True, but when you remove the red color as genre color it should do the job.
btw. how do people know which color stands for what genre? (other than getting familiar with the color icw the kind of programme)

**Comment by jeroenpardon** [comment]
> True, but when you remove the red color as genre color it should do the job.

As an indicator I feel a marking of some sort is clearer.

> btw. how do people know which color stands for what genre? (other than getting familiar with the color icw the kind of programme)

Pretty much that :) Kodi sets [a number](https://github.com/jeroenpardon/skin.grid/blob/master/media/pvr/genres/README.md) on the programme that indicates the genre, which is then used to attach a certain color. I don't believe there is an official standard of some sort, but when first setting up the PVR in my previous skin, I did choose colors that were somewhat similar to Kodi's default skin at the time.

**Comment by Joostzilla** [comment]
> As an indicator I feel a marking of some sort is clearer.

Okay. You are the GRID master. Too bad we can't use texture. :-)

>Pretty much that :) Kodi sets a number on the programme that indicates the genre, which is then used to attach a certain color. I don't believe there is an official standard of some sort, but when first setting up the PVR in my previous skin, I did choose colors that were somewhat similar to Kodi's default skin at the time.

The colors that you use in GRID fit the skin very well. But what genres are included in the providers tvstream isn't sure. So maybe there should be a genre color off option.

If i repeat myself i am sorry. That's because my memory is really bad. No kidding.

**Comment by jeroenpardon** [comment]
recording / timer indicator was added, colours will likely be tweaked
