### ISSUE TITLE
Homescreen fanart background disappears when playing Radio

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#146]
Homescreen fanart background disappears when playing Radio

**Comment by jeroenpardon** [comment]
I can't reproduce this one

**Comment by Joostzilla** [comment]
Strange, iirc there was an other user reporting the same issue.

**Comment by jeroenpardon** [comment]
Only mention I see currently is about #140

**Comment by jeroenpardon** [comment]
Possibly I fixed this "by accident" somewhere between the official release and my dev version? Please check if the problem still exists when the new beta is out :)

**Comment by Joostzilla** [comment]
Haha, i will check asap when beta is out.
Any idea when?

**Comment by jeroenpardon** [comment]
If you ask me now, this week.

I’m terrible with deadlines though ;)

**Comment by Joostzilla** [comment]
Just take your time. Deadlines are terrible 😀
