### ISSUE TITLE
Missing list-landscape view in TVseries seasons

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#147]
In TVseries seasons i miss List-landscape view.
Having this view with a season plot summary would be greatly appreciated :-)
Also the Label2 isn't occupied. It could have information like:
year, episodes, genre, unwatched episodes

![image](https://user-images.githubusercontent.com/1034920/31993715-5f0020aa-b97e-11e7-8eaa-79ccb5ab3d04.png)

**Comment by jeroenpardon** [comment]
Agreed, 2546e6294d4ef5f22bb1b2d3703434d6a1102fa3 takes care of this.

**Comment by Joostzilla** [comment]
>Agreed, 2546e62 takes care of this.

The number links to xml code. I guess this will be included in the new beta :) 
Or can i do something with the code?

**Comment by jeroenpardon** [comment]
That's just a way to document / reference the commit that solves the issue :)

Will be in the new beta yes, but you can always grab a snapshot build from GitHub. That will always contain any changes like this one. 

More info on that [here](https://github.com/jeroenpardon/skin.grid#download)

**Comment by Joostzilla** [comment]
Much obliged 😀

**Comment by Joostzilla** [comment]
But i think i just wait for your beta. :-)
