### ISSUE TITLE
Let info from paused video disappear after a few seconds

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#149]
A lot of times when i pause video it is to look at a detail on the screen. Currently the info at the bottom blocks a lot of the screen.

**Comment by jeroenpardon** [comment]
This is a really subjective thing. Hiding the info automatically after a couple of seconds will not be in favour of people wanting to read plot descriptions for example.

The best I could do in this regard is to provide a skin setting that hides the info when pausing (always).

**Comment by Joostzilla** [comment]
Plot description is always available in the pop up menu.
But a skin setting for always hide is imho a great solution.

**Comment by jeroenpardon** [comment]
df2189674b5d3216e9dd92c5f273831c765b109e takes care of this

**Comment by Joostzilla** [comment]
In the latest beta the button in settings does nothing.

**Comment by jeroenpardon** [comment]
It does for me? Checking this option hides the onscreen media information when pressing pause.

**Comment by Joostzilla** [comment]
When i press pause the info is indeed gone. That's perfect. But when enabling/disabling the button nothing changes in function.

I use the latest snapshot iirc.

**Comment by jeroenpardon** [comment]
Do you mean the setting isn’t changed back? Or that the button doesn’t indicate wether it’s set to enabled or not? You should see a radiobutton, if not something is wrong. In that case please grab from git again

**Comment by Joostzilla** [comment]
I see the radio button but indeed it doesn't indicate the current state.
Will check tommorow. 
Grid is use now :-)
