### ISSUE TITLE
Problem with reaching the sidebar in full TVguide

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#150]
>- When viewing the full EPG/guide, in Titan when you press the 'back' button the first time it pops open the side bar.  This allows for changing of channel groups easily.  Pressing it a second time will then perform the back function.  Is something like this possible?  Does anyone have any suggestions for how I could add it easily if not?  Opening the sidebar in the EPG seems to be a little problematic, especially with the 'lingertime' option now being in days (rather than the previous minutes setting, allowing a small lingertime on the epg to allow you to press 'left' to open the sidebar easily) and as far as I can tell the advancedsettings options being deprecated anyway. 

>EDIT: It seems this 'hack' works for now, setting a lingertime of 30 minutes, allows pressing left on the EPG to pop open the sidebar easily, but seems to be deprecated in v18.

I didn't even know there was a sidebar available in TVguide because i couldn't reach it. :-D

**Comment by jeroenpardon** [comment]
Using the Menu / M button also opens the menu. Anyway, I'll have to think about how I'm going to tackle this one.

**Comment by Joostzilla** [comment]
It is a hard one to figure out indeed. In MediaPortal there is no sidemenu in the Guide. So i never thought to look for one in Grid. Pressing M is for me pretty easy to map to my Harmony. But i guess a lot of users use less advanced remotes.
How about pressing left long?

**Comment by jeroenpardon** [comment]
Posted this a possible solution on the forum, afaik skin cannot assign longpresses.
