### ISSUE TITLE
'Play Recording' not focused on recording info screen

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#151]
When choosing to play a recording the 'Play Recording' button isn't focused on the info page.

![image](https://user-images.githubusercontent.com/1034920/32143306-9c29fb5a-bca7-11e7-8acc-dea05c7f7764.png)

**Comment by jeroenpardon** [comment]
f4b401ac08ec2067b439f6e417943c4631ce2fac takes care of this, cheers!
