### ISSUE TITLE
Use left/right to change channel groups miniguide

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#153]
after a time of using Grid i noticed it would be very convenient to be able to switch from the mini channel guide to the mini programme guide by pressing left/right.

![image](https://user-images.githubusercontent.com/1034920/32165527-6026c91e-bd63-11e7-90c3-91b896c52438.png)
![image](https://user-images.githubusercontent.com/1034920/32165555-72574cd0-bd63-11e7-857f-aaae6a5f43da.png)

**Comment by jeroenpardon** [comment]
I'm going to have to say no to this as there are already plans to switch channel groups using left/right, sorry.

**Comment by Joostzilla** [comment]
Okay. No problem

**Comment by Joostzilla** [comment]
Btw. Is it possible to get Radio channels also as group in the mini guide?
That's how it works on most TV's too. 
The left/right changing groups works flawless.

**Comment by jeroenpardon** [comment]
The actual grouping of channels is done in Kodi core and the skin code for the channel guide is not specific to either radio or tv. So if it's possible (and I am assuming it is) the skin doesn't need to provide additional support for it. I believe you the group manager is where you'll need to be.

**Comment by Joostzilla** [comment]
In the groupmanager there is one default group called 'All Channels'. Unfortunately it does not show any channel.
When creating a new group e.g. 'Television' the TV channels appear in the 'hidden' channels. When you click these channels they don't appear in the 'visible channels'. 
And above all, only TV channels are available in the group manager. Radio channels aren't.

**Comment by jeroenpardon** [comment]
Yea, it's a little...weird. So, in the channel manager you can switch from tv channels to radio channels. Then when you go into the group manager you can edit the radio channel groups. 
I have made some changes to the channel manager for the next release. I added a button in the channel manager that will allow you to jump to the group manager. It would make far more sense if there would be a way to switch from tv to radio within the group manager window (too). Unfortunately that is beyond my control.

**Comment by Joostzilla** [comment]
>So, in the channel manager you can switch from tv channels to radio channels. Then when you go into the group manager you can edit the radio channel groups.

I will investigate further tomorrow. 
Btw. In channel manager i think its counter intuitive that you see the button Radio channels when the list shows the TV channels and vice versa. Maybe showing 2 radio buttons for TV channels and Radio channels is more clear.

How the grouping works is also dependant of the PVR backend.

**Comment by jeroenpardon** [comment]
I feel you would want to know what a button is going to do instead of what it has done? It is showing tv channels and pressing the button will switch to radio channels. 2 radio buttons take up too much space and move the last option out of screen bounds. 
Changing the label on the button might make the function clearer, something like "switch to radio channels".

**Comment by Joostzilla** [comment]
Changing the label is indeed the best option. :-)

**Comment by Joostzilla** [comment]
The new channel manager looks great and intuitive. Unfortunately the group manager isn't working for me. Yes, i can see the hidden channels in both Television as Radio group but selecting them doesn't shift them to the visible channels column.
In LiveTV i can switch between 'All Channels' and 'Television' in the miniguide though. The radio group is not available.
In the Radio section of Kodi i can switch between 'All Channels' and 'Radio'. All channels also shows only radio channels.
For me this is no problem but i can imagine it's something for the Kodi dev team to look at.

**Comment by Joostzilla** [comment]
btw. i moved the view radio stations i listen to the Grid favourites. Gives me more options to view the thumbs.
Although fanart support for radio is not very well (or actually absent) in Kodi.

**Comment by jeroenpardon** [comment]
I’ll do a check on the group manager, but can’t change the rest, that is handled by Kodi core

________________________________

**Comment by jeroenpardon** [comment]
See #154
