### ISSUE TITLE
First run setup – question about last/final step

### ISSUE THREAD

**Issue by Ostrymiecz** [jeroenpardon/skin.grid#156]
At last/final step there are two buttons that were present also in first step ("No, not now" and "Yes, take me there"). I think this is misleading for new user and for sure strings used for those buttons doesn't fit text description above them (in last step).

In last step I'd change the button "No, not now" to "OK, let's start!" which would close first run setup and second button could be "Go to skin settings". Then everything would be clear for user.

**Comment by jeroenpardon** [comment]
Strings adjusted / finalized in latest commits
