### ISSUE TITLE
Horizontal menu bug?

### ISSUE THREAD

**Issue by Ostrymiecz** [jeroenpardon/skin.grid#160]
I'm using latest Grid "beta" from this repo and after recent update (when Hubs were introduced) something went wrong with horizontal menu.

When I hover System menu and press down arrow to go to the submenu, whole menu slides up to middle of screen rather than just switch to submenu. It should be like this?

Tried resetting menu to default but that didn't helped.

**Comment by jeroenpardon** [comment]
Can't reproduce this, tried with and without widgets enabled. Home menu code hasn't seen any changes in recent updates, so not sure what could be causing it tbh

**Comment by Ostrymiecz** [comment]
So I must try resetting all settings to default.

**Comment by jeroenpardon** [comment]
Any luck with narrowing this one down?

**Comment by Ostrymiecz** [comment]
No 😢 I've even downgraded Colorbox add-on and no luck at all. Give me just a moment and I will record short video to show You this weird behavior. Maybe I wrote this ticket badly in first post.

Hold on…

**Comment by Ostrymiecz** [comment]
See this video Jeroen: https://youtu.be/biGUMY4JJXM

**Comment by Ostrymiecz** [comment]
Any ideas what went wrong Jeroen?

**Comment by Ostrymiecz** [comment]
I just tested it once again and did:
1. Removed Grid add-on from Kodi
2. Removed all skin.grid* directories from HDD
3. Reinstalled Grid v1.5.1 from official repo

and bug still exists. WTF?!?

**Comment by jeroenpardon** [comment]
So it happens on the system submenu only? Looks like as if there is a widget on that menu item that can't be loaded or something. Try clearing out %kodiprofile%\userdata\addon_data\script.skinshortcuts

warning: this will remove any home menu customizations

**Comment by Ostrymiecz** [comment]
Currently it happens only on system submenu because it's my only submenu. I'll try clearing out mentioned folder and also adding other submenus.

**Comment by Ostrymiecz** [comment]
Just tested it:
1. Added other sumbenu and it's the same.
2. Cleared out %kodiprofile%\userdata\addon_data\script.skinshortcuts folder and booted Kodi. Menu was recreated and still same bug.

**Comment by Ostrymiecz** [comment]
Don't know if it's important but after the menu slides up and you're in submenu (so submenu item is "hovered") there is something like third bar beneath submenu.

**Comment by jeroenpardon** [comment]
There's a file called script-skinshortcuts-includes.xml in the skin's xml folder, can you upload that?

**Comment by Ostrymiecz** [comment]
Yes, but as soon as I get back home after work. This bug is super weird.

About script-skinshortcuts-includes.xml file. Shoulnd't this file be fresh or created/recreated while I was installing fresh Grid? Because I did fresh skin install and it didn't helped. And yes I cleared all Grid's folders in Kodi dir and profile dir.

**Comment by Ostrymiecz** [comment]
Here it is [script-skinshortcuts-includes.zip](https://github.com/jeroenpardon/skin.grid/files/1668448/script-skinshortcuts-includes.zip)

**Comment by Ostrymiecz** [comment]
And here's a screenshot with debug info on main screen.
![screen](https://user-images.githubusercontent.com/1296598/35525482-85ebcb9e-051c-11e8-8bac-44de140cdf5c.jpg)

**Comment by jeroenpardon** [comment]
yeah the debug info doesn't really say anything about the home menu. I will look into this further once I get the chance, available time is very limited atm.

**Comment by Ostrymiecz** [comment]
When submenu scrolls whole menu to the middle of the screen debug info stays the same. So, yeah, it doesn't help in this case.

**Comment by Ostrymiecz** [comment]
Notice something like a third row (marked in red) under a submenu. Don't know if it should be there or not.  
![screenshot000](https://user-images.githubusercontent.com/1296598/35638210-ce34ea8e-06b6-11e8-807c-54ae0a216960.jpg)

**Comment by hoppel118** [comment]
I am in the same situation. I am using the horizontal menu and when I press the down arrow to go to the submenu, the whole menu slides up into the middle of the screen. But I thought this is the default per design. I prefer it this way really. It makes the skin more dynamic.  

![screen shot 2018-03-05 at 22 39 12](https://user-images.githubusercontent.com/991344/37001255-361c8700-20c6-11e8-8bb5-0355131da289.png)

![screen shot 2018-03-05 at 22 39 20](https://user-images.githubusercontent.com/991344/37001262-3c2b8240-20c6-11e8-85a6-19df77343367.png)

Greetings Hoppel

**Comment by jeroenpardon** [comment]
now that part of the horizontal menu structure has been reworked I am assuming this is not an issue anymore?

**Comment by Ostrymiecz** [comment]
Woohoo! Grid 1.6.0 fixes this issue. Yay! 👏

**Comment by jeroenpardon** [comment]
👍
