### ISSUE TITLE
Request: Episode numbering for the "slide" view

### ISSUE THREAD

**Issue by olavinto** [jeroenpardon/skin.grid#161]
### Description

For other views there seems to be episode numbers but the slide view does not. Maybe an oversight? It would be nice to see where in the list one is browsing it, wouldn't it?

GRiD is one of the most polished skins I've used. Many skins try to do everything although much of it is often completely useless. Thank you very much for your great contribution! :-)

### Checklist:

- [X] I have checked if I am using the latest version of Grid at the time of opening this issue
- [X] I am running a Kodi version that is listed as compatible in Grid's README file
- [X] I have checked if all of the [required add-ons](https://github.com/jeroenpardon/skin.grid.beta/wiki/Required-and-supported-add-ons) are installed on my system
- [X] I have checked whether this behaviour is also present in Kodi's default skin
- [ ] I have screenshots or a video for further explanation. I have included a link to the image(s) or video in my description 
- [ ] I have a debug log for (further) explanation. I have included a link to the log on pastebin.com or similar service in my description

**Comment by jeroenpardon** [comment]
Thanks, glad your enjoying the skin :) Can't check it right now, but I agree the view should show the episode number. So yeah, it's probably an oversight, will look into it, cheers.

**Comment by jeroenpardon** [comment]
Should be taken care of by 21506e4c0873c4f3f9fea132d347973469b46904
