### ISSUE TITLE
Vertical widget focus 2.3.1

### ISSUE THREAD

**Issue by snoopyjoe** [jeroenpardon/skin.grid#166]
The screen height on the vertical widget screen is not registering as 1080. This was causing the widget focus to be off by one line. So when scrolling down the highlighted widget was not the visable widget on the screen. The **$PARAM[Height]** at line 281 in Includes_Home.xml is not getting the height param for some reason. I used the **screen_Height** variable, which is 1080, instead and that resolved the issue. I'm running LE9 alpha with Kodi 18. Also as seen in the last picture, when a video ask to resume from a last resume time, the dialog focus is off screen.

I'm not good with XML and skins so creating a fork for one line of code wasn't necessary. Python is my expertise.

![img_20180306_021037](https://user-images.githubusercontent.com/18134695/37080295-955b085c-219a-11e8-9d11-2a8dc974dadf.jpg)
![img_20180306_021047](https://user-images.githubusercontent.com/18134695/37080296-957d2298-219a-11e8-8e69-c59347638a8a.jpg)
![img_20180206_004920](https://user-images.githubusercontent.com/18134695/37080294-9536ada4-219a-11e8-83f8-5763e195ff95.jpg)

 
### Checklist:

- [X ] I have checked if I am using the latest version of Grid at the time of opening this issue
- [X ] I am running a Kodi version that is listed as compatible in Grid's README file
- [X ] I have checked if all of the [required add-ons](https://github.com/jeroenpardon/skin.grid.beta/wiki/Required-and-supported-add-ons) are installed on my system
- [X ] I have checked whether this behaviour is also present in Kodi's default skin
- [ X] I have screenshots or a video for further explanation. I have included a link to the image(s) or video in my description 
- [ ] I have a debug log for (further) explanation. I have included a link to the log on pastebin.com or similar service in my description

**Comment by jeroenpardon** [comment]
I have a fix lined up for this, bear with me

**Comment by jeroenpardon** [comment]
fix in 3cabb45cd9ba42b9c7d47c8984cdef191f07a741
