### ISSUE TITLE
Feature Request - Episode Number in TV Slide View

### ISSUE THREAD

**Issue by bigdaddyral** [jeroenpardon/skin.grid#168]
### Description

Sorry I've been AWOL for so long, you've done a beautiful job with this skin and I'm grateful whenever I get to use it!

For the Recent Episodes menu item I use the slide view, is there a way to add the episode number to this view?

Thanks for listening!

### Checklist:

- [ X ] I have checked if I am using the latest version of Grid at the time of opening this issue
- [ X ] I am running a Kodi version that is listed as compatible in Grid's README file
- [ X ] I have checked if all of the [required add-ons](https://github.com/jeroenpardon/skin.grid.beta/wiki/Required-and-supported-add-ons) are installed on my system
- [ X ] I have checked whether this behaviour is also present in Kodi's default skin
- [ ] I have screenshots or a video for further explanation. I have included a link to the image(s) or video in my description 
- [ ] I have a debug log for (further) explanation. I have included a link to the log on pastebin.com or similar service in my description

**Comment by bigdaddyral** [comment]
Ya know, on a hunch, I looked at closed issues and saw that this has been addressed. I'm going to mess with things, maybe uninstall and reinstall the skin and see if it fixes it...

**Comment by jeroenpardon** [comment]
The issue should be resolved yes, but only in beta / git releases at the moment and I don't remember if I backported the fix to the Krypton release already. Haven't been able to look into it yet because of moving house, will investigate asap. Good to see you back :)

**Comment by bigdaddyral** [comment]
That makes sense. I played with it a bit before I left town and couldn't get it to show up. I see that you issued a new release today, I'll ask my wife to check and see if it's fixed in Krypton.
