### ISSUE TITLE
Skin failed to install on Leia

### ISSUE THREAD

**Issue by gofirst2220** [jeroenpardon/skin.grid#169]
### Description
Skin Failed to Install on Leia when manually install it from zip file. So the Skin is gone from the Skin selection menu. I wonder if there is something wrong.

Added debug log [here](https://pastebin.com/BeJj6TNb)
### Checklist:

- [X] I have checked if I am using the latest version of Grid at the time of opening this issue
- [X] I am running a Kodi version that is listed as compatible in Grid's README file
- [X] I have checked if all of the [required add-ons](https://github.com/jeroenpardon/skin.grid.beta/wiki/Required-and-supported-add-ons) are installed on my system
- [X] I have checked whether this behaviour is also present in Kodi's default skin
- [ ] I have screenshots or a video for further explanation. I have included a link to the image(s) or video in my description 
- [X] I have a debug log for (further) explanation. I have included a link to the log on pastebin.com or similar service in my description

**Comment by jeroenpardon** [comment]
debug log please

**Comment by gofirst2220** [comment]
@jeroenpardon added debug log. the issue might be somewhere in the log as its the whole log

**Comment by jeroenpardon** [comment]
Sorry for the late reply. Could you try pulling from Github? Updating through the repo add-on has been problematic at times

https://github.com/jeroenpardon/skin.grid/archive/Leia.zip

**Comment by Lyechee** [comment]
Had the same problem, works now with the github version, thanks
