### ISSUE TITLE
Impossible to find LibreElec settings

### ISSUE THREAD

**Issue by bruere-s** [jeroenpardon/skin.grid#171]
### Description
I'm am on Kodi 17 on a Raspberry 3. I want to connect to a bluetooth speaker. But I can't find the bluetooth settings, normally localised in the libreelec settings.
Can you show me where to find these settings ?

Thanks in advance

### Checklist:

- [X] I have checked if I am using the latest version of Grid at the time of opening this issue
- [X] I am running a Kodi version that is listed as compatible in Grid's README file
- [ ] I have checked if all of the [required add-ons](https://github.com/jeroenpardon/skin.grid.beta/wiki/Required-and-supported-add-ons) are installed on my system
- [X] I have checked whether this behaviour is also present in Kodi's default skin
- [ ] I have screenshots or a video for further explanation. I have included a link to the image(s) or video in my description 
- [ ] I have a debug log for (further) explanation. I have included a link to the log on pastebin.com or similar service in my description

**Comment by jeroenpardon** [comment]
IIRC the LibreElec settings is a regular add-on, so you should be able to find it in your program add-ons. For easy access you could add it to your home menu. 
Please use the forum for support, thanks.
