### ISSUE TITLE
OSD settings audio/video lose focus when video is in pause with information

### ISSUE THREAD

**Issue by ibox99** [jeroenpardon/skin.grid#172]
### Description
when we are watching a video and pause it to go to the "options menu", this option menu apears in focus, but if we select the audio or video sub-option then the video information stays on top, making the osd of video/audio out of focus but working.

### Reproduction
play some video, pause it with enter and go to suboption menu of audio/video

See this happening in KODI 17 and 18, with the respective GRID

### Checklist:

- [X] I have checked if I am using the latest version of Grid at the time of opening this issue
- [x] I am running a Kodi version that is listed as compatible in Grid's README file
- [ ] I have checked if all of the [required add-ons](https://github.com/jeroenpardon/skin.grid.beta/wiki/Required-and-supported-add-ons) are installed on my system
- [ ] I have checked whether this behaviour is also present in Kodi's default skin
- [X] I have screenshots or a video for further explanation. I have included a link to the image(s) or video in my description 
- [ ] I have a debug log for (further) explanation. I have included a link to the log on pastebin.com or similar service in my description

![osdproblem](https://user-images.githubusercontent.com/17782109/43328078-04bdb44e-91b5-11e8-9736-7b9774e5f910.jpg)

**Comment by jeroenpardon** [comment]
Can't replicate on Leia. If you're using a mouse, then that is likely the issue.
